### ISSUE TITLE
Deeplink is broken after auto authentication

### ISSUE THREAD

**Issue by pdegand** [octo-wam/moss-front#4]
🗒 Be un-authenticated
Click a deeplink to a specific poll (https://octo-moss.netlify.com/question/e521e04d-3d2d-4b5e-9214-ac804b8581e2) 

❌ You are automatically authenticated but end up on the home page

✅ You should be automatically authenticated and end up on the requested poll

**Comment by OctoMaieonBrixxy** [comment]
Hello,

Nous (ALME et YCWA) avons trouvé plusieurs solution pour intégrer cette nouvelle feature : 

La royale : 

- ajout de l'url de "départ" en tant que paramètre à l'url d'authentification 

```javascript
export function redirectToLoginPage() {
  window.location.href = `${LOGIN_PAGE_URL}?redirect_uri=${window.location.href}`;
}
```
- Récupération côté back de l'url de redirection et on redirige l'utilisateur directement ici https://github.com/octo-wam/moss-back/blob/d195e207c7fd069fd9363c077586ec3fbcc25ac5/app/controllers/google_oauth_callback_controller.rb 

**La fronteuse** : 

- on stock dans le localStorage, avant redirection, la dernière url visitée 
- au retour d'une authentification réussie, on check le localStorage et on redirige

@antoinechalifour
